services:
  modbus-server:
    image: oitc/modbus-server:latest
    ports:
      - 5020:5020
  influxdb:
    image: influxdb:2
    ports:
    - 8086:8086
    volumes:
    - ./config/modbus_server.json:/app/modbus_server.json:ro