services:
  influxdb:
    image: influxdb:2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: poc
      DOCKER_INFLUXDB_INIT_BUCKET: poc
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: poc
    ports:
    - 8086:8086
  modbus-server:
    image: oitc/modbus-server:latest
    ports:
    - 5020:5020
    volumes:
    - ./config/modbus_server.json:/app/modbus_server.json
    depends_on:
    - influxdb
  integration-svc:
    build:
      dockerfile: Dockerfile.integration
      no_cache: true
    ports:
    - 8081:8080
    restart: on-failure
    environment:
    - MODBUS_HOST=modbus-server
    - MODBUS_PORT=5020
    - INFLUX_HOST=influxdb
    - INFLUX_PORT=8086
    depends_on:
      modbus-server:
        condition: service_started
  measurement-svc:
    build:
      dockerfile: Dockerfile.measurement
      no_cache: true
    ports:
    - 8082:8080
    environment:
    - INFLUX_HOST=influxdb
    - INFLUX_PORT=8086
    depends_on:
    - integration-svc