# Stage 1: Build
FROM golang:1.26-alpine3.23 AS builder

WORKDIR /app

COPY measurement-svc/ ./measurement-svc/
RUN cd measurement-svc && go mod download

COPY shared/ ./shared/
RUN cd shared && go mod download

COPY . .
RUN go build -o measurement-service measurement-svc/cmd/app/main.go

# Stage 2: Run
FROM alpine:3.23

WORKDIR /app

COPY --from=builder /app/measurement-service ./measurement-service

EXPOSE 8080

CMD ["./measurement-service"]