# Stage 1: Build
FROM golang:1.26-alpine3.23 AS builder

WORKDIR /app

COPY shared/ ./shared/
RUN cd shared && go mod download

COPY integration-svc/ ./integration-svc/
RUN cd integration-svc && go mod download

COPY . .
RUN go build -o integration-service integration-svc/cmd/app/main.go

# Stage 2: Run
FROM alpine:3.23

WORKDIR /app

COPY --from=builder /app/integration-service ./integration-service

EXPOSE 8080

CMD ["./integration-service"]