// Code generated by counterfeiter. DO NOT EDIT.
package assetfakes

import (
	"context"
	"stellar-integration/pkg/domain/asset"
	"sync"
)

type FakeAssetRepository struct {
	PostAssetByIDStub        func(context.Context, *asset.Asset, string) error
	postAssetByIDMutex       sync.RWMutex
	postAssetByIDArgsForCall []struct {
		arg1 context.Context
		arg2 *asset.Asset
		arg3 string
	}
	postAssetByIDReturns struct {
		result1 error
	}
	postAssetByIDReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAssetRepository) PostAssetByID(arg1 context.Context, arg2 *asset.Asset, arg3 string) error {
	fake.postAssetByIDMutex.Lock()
	ret, specificReturn := fake.postAssetByIDReturnsOnCall[len(fake.postAssetByIDArgsForCall)]
	fake.postAssetByIDArgsForCall = append(fake.postAssetByIDArgsForCall, struct {
		arg1 context.Context
		arg2 *asset.Asset
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.PostAssetByIDStub
	fakeReturns := fake.postAssetByIDReturns
	fake.recordInvocation("PostAssetByID", []interface{}{arg1, arg2, arg3})
	fake.postAssetByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAssetRepository) PostAssetByIDCallCount() int {
	fake.postAssetByIDMutex.RLock()
	defer fake.postAssetByIDMutex.RUnlock()
	return len(fake.postAssetByIDArgsForCall)
}

func (fake *FakeAssetRepository) PostAssetByIDCalls(stub func(context.Context, *asset.Asset, string) error) {
	fake.postAssetByIDMutex.Lock()
	defer fake.postAssetByIDMutex.Unlock()
	fake.PostAssetByIDStub = stub
}

func (fake *FakeAssetRepository) PostAssetByIDArgsForCall(i int) (context.Context, *asset.Asset, string) {
	fake.postAssetByIDMutex.RLock()
	defer fake.postAssetByIDMutex.RUnlock()
	argsForCall := fake.postAssetByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAssetRepository) PostAssetByIDReturns(result1 error) {
	fake.postAssetByIDMutex.Lock()
	defer fake.postAssetByIDMutex.Unlock()
	fake.PostAssetByIDStub = nil
	fake.postAssetByIDReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAssetRepository) PostAssetByIDReturnsOnCall(i int, result1 error) {
	fake.postAssetByIDMutex.Lock()
	defer fake.postAssetByIDMutex.Unlock()
	fake.PostAssetByIDStub = nil
	if fake.postAssetByIDReturnsOnCall == nil {
		fake.postAssetByIDReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postAssetByIDReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAssetRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAssetRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ asset.AssetRepository = new(FakeAssetRepository)
