// Code generated by counterfeiter. DO NOT EDIT.
package assetfakes

import (
	"context"
	"stellar-measurement/pkg/domain/asset"
	"sync"
)

type FakeAssetRepository struct {
	GetAssetByIDStub        func(context.Context, string, string) (*asset.Asset, error)
	getAssetByIDMutex       sync.RWMutex
	getAssetByIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}
	getAssetByIDReturns struct {
		result1 *asset.Asset
		result2 error
	}
	getAssetByIDReturnsOnCall map[int]struct {
		result1 *asset.Asset
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAssetRepository) GetAssetByID(arg1 context.Context, arg2 string, arg3 string) (*asset.Asset, error) {
	fake.getAssetByIDMutex.Lock()
	ret, specificReturn := fake.getAssetByIDReturnsOnCall[len(fake.getAssetByIDArgsForCall)]
	fake.getAssetByIDArgsForCall = append(fake.getAssetByIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetAssetByIDStub
	fakeReturns := fake.getAssetByIDReturns
	fake.recordInvocation("GetAssetByID", []interface{}{arg1, arg2, arg3})
	fake.getAssetByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAssetRepository) GetAssetByIDCallCount() int {
	fake.getAssetByIDMutex.RLock()
	defer fake.getAssetByIDMutex.RUnlock()
	return len(fake.getAssetByIDArgsForCall)
}

func (fake *FakeAssetRepository) GetAssetByIDCalls(stub func(context.Context, string, string) (*asset.Asset, error)) {
	fake.getAssetByIDMutex.Lock()
	defer fake.getAssetByIDMutex.Unlock()
	fake.GetAssetByIDStub = stub
}

func (fake *FakeAssetRepository) GetAssetByIDArgsForCall(i int) (context.Context, string, string) {
	fake.getAssetByIDMutex.RLock()
	defer fake.getAssetByIDMutex.RUnlock()
	argsForCall := fake.getAssetByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAssetRepository) GetAssetByIDReturns(result1 *asset.Asset, result2 error) {
	fake.getAssetByIDMutex.Lock()
	defer fake.getAssetByIDMutex.Unlock()
	fake.GetAssetByIDStub = nil
	fake.getAssetByIDReturns = struct {
		result1 *asset.Asset
		result2 error
	}{result1, result2}
}

func (fake *FakeAssetRepository) GetAssetByIDReturnsOnCall(i int, result1 *asset.Asset, result2 error) {
	fake.getAssetByIDMutex.Lock()
	defer fake.getAssetByIDMutex.Unlock()
	fake.GetAssetByIDStub = nil
	if fake.getAssetByIDReturnsOnCall == nil {
		fake.getAssetByIDReturnsOnCall = make(map[int]struct {
			result1 *asset.Asset
			result2 error
		})
	}
	fake.getAssetByIDReturnsOnCall[i] = struct {
		result1 *asset.Asset
		result2 error
	}{result1, result2}
}

func (fake *FakeAssetRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAssetRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ asset.AssetRepository = new(FakeAssetRepository)
