name: Acceptance Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v4
    - name: Run acceptance tests
      run: make integration-e2e-tests cleanup-containers measurement-e2e-tests cleanup-containers gateway-e2e-tests