name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v4
    - name: Run e2e tests
      shell: bash
      run: |
        set -ex
        make integration-e2e-tests cleanup-containers
        sleep 10
        make measurement-e2e-tests cleanup-containers
        sleep 10
        make gateway-e2e-tests